package constants

// actions constants
const (
	// auth
	LOGIN       = "LOGIN"
	LOGOUT      = "LOGOUT"
	AUTH_ACTION = "AUTHENTICATION"

	// mpin
	RESET_MPIN  = "RESET_MPIN"
	FORGOT_MPIN = "FORGOT_MPIN"
	VERIFY_MPIN = "VERIFY_MPIN"
	UPDATE_MPIN = "UPDATE_MPIN"

	// debit-card
	DEBIT_CARD_PIN_RESET         = "DEBIT_CARD_PIN_RESET"
	DEBIT_CARD_TRANSACTION_LIMIT = "DEBIT_CARD_TRANSACTION_LIMIT"
	DEBIT_CARD_BLOCK_UNBLOCK     = "DEBIT_CARD_BLOCK_UNBLOCK"

	// consent
	BANK_CONSENT = "BANK_CONSENT"

	//Address Update
	ADDRESS_UPDATE = "ADDRESS_UPDATE"

	//CHANGE UPI PIN Update
	CHANGE_UPI_PIN = "CHANGE_UPI_PIN"

	// nominee
	UPDATE_NOMINEE = "UPDATE_NOMINEE"
	NEW_NOMINEE    = "NEW_NOMINEE"

	//REMAPPING UPI ID
	REMAPPING_UPI_ID = "REMAPPING_UPI_ID"

	//SIM-BINDING SMS VERIFICATION
	SIM_BINDING_SMS_VERIFICATION = "SIM_BINDING_SMS_VERIFICATION"

	// faq
	FAQ = "FAQ"
)
