// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: rpc/payment-service.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaymentService_GetReceiptId_FullMethodName              = "/rpc.PaymentService/GetReceiptId"
	PaymentService_UpdatePaymentState_FullMethodName        = "/rpc.PaymentService/UpdatePaymentState"
	PaymentService_GetDebitCardPaymentStatus_FullMethodName = "/rpc.PaymentService/GetDebitCardPaymentStatus"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	GetReceiptId(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayServiceResponse, error)
	UpdatePaymentState(ctx context.Context, in *PaymentStatusRequest, opts ...grpc.CallOption) (*PaymentStatusResponse, error)
	GetDebitCardPaymentStatus(ctx context.Context, in *GetDebitCardPaymentStatusRequest, opts ...grpc.CallOption) (*GetDebitCardPaymentStatusResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GetReceiptId(ctx context.Context, in *GatewayRequest, opts ...grpc.CallOption) (*GatewayServiceResponse, error) {
	out := new(GatewayServiceResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetReceiptId_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) UpdatePaymentState(ctx context.Context, in *PaymentStatusRequest, opts ...grpc.CallOption) (*PaymentStatusResponse, error) {
	out := new(PaymentStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_UpdatePaymentState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetDebitCardPaymentStatus(ctx context.Context, in *GetDebitCardPaymentStatusRequest, opts ...grpc.CallOption) (*GetDebitCardPaymentStatusResponse, error) {
	out := new(GetDebitCardPaymentStatusResponse)
	err := c.cc.Invoke(ctx, PaymentService_GetDebitCardPaymentStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility
type PaymentServiceServer interface {
	GetReceiptId(context.Context, *GatewayRequest) (*GatewayServiceResponse, error)
	UpdatePaymentState(context.Context, *PaymentStatusRequest) (*PaymentStatusResponse, error)
	GetDebitCardPaymentStatus(context.Context, *GetDebitCardPaymentStatusRequest) (*GetDebitCardPaymentStatusResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentServiceServer struct {
}

func (UnimplementedPaymentServiceServer) GetReceiptId(context.Context, *GatewayRequest) (*GatewayServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReceiptId not implemented")
}
func (UnimplementedPaymentServiceServer) UpdatePaymentState(context.Context, *PaymentStatusRequest) (*PaymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePaymentState not implemented")
}
func (UnimplementedPaymentServiceServer) GetDebitCardPaymentStatus(context.Context, *GetDebitCardPaymentStatusRequest) (*GetDebitCardPaymentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDebitCardPaymentStatus not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_GetReceiptId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetReceiptId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetReceiptId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetReceiptId(ctx, req.(*GatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_UpdatePaymentState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).UpdatePaymentState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_UpdatePaymentState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).UpdatePaymentState(ctx, req.(*PaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetDebitCardPaymentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDebitCardPaymentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetDebitCardPaymentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetDebitCardPaymentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetDebitCardPaymentStatus(ctx, req.(*GetDebitCardPaymentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReceiptId",
			Handler:    _PaymentService_GetReceiptId_Handler,
		},
		{
			MethodName: "UpdatePaymentState",
			Handler:    _PaymentService_UpdatePaymentState_Handler,
		},
		{
			MethodName: "GetDebitCardPaymentStatus",
			Handler:    _PaymentService_GetDebitCardPaymentStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/payment-service.proto",
}
